[package]
name = "mangadex-desktop-api2"
version = "1.0.0-alpha.1"
authors = ["tonymushah <tonymushahdev06@yahoo.com>"]
license = "MIT OR Apache-2.0"
description = "A Actix server for downloading manga, chapters, covers from Mangadex"
repository = "https://github.com/tonymushah/eureka-mmanager"
edition = "2021"
resolver = "2"
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12", features = [
    "cookies",
    "json",
    "multipart",
    "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.8", features = ["serde", "v4"] }
url = { version = "2.5", features = ["serde"] }
mangadex-api = { version = "3.3", default-features = false, features = [
    "rw-multi-thread",
    "utils",
    "serialize",
] }
anyhow = "1.0"
serde_json = "1.0"
mangadex-api-schema-rust = { version = "0.9", default-features = false, features = [
    "serialize",
] }
mangadex-api-types-rust = { version = "0.9", default-features = false }
tokio = { version = "1.37", features = [
    "sync",
    "rt",
    "macros",
    "rt-multi-thread",
] }
log = "^0.4.21"
tokio-stream = { version = "0.1" }
async-stream = { version = "0.3" }
bytes = { version = "1.6" }
itertools = "0"
fern = { version = "0.6", optional = true }
mangadex-api-input-types = { version = "0.5" }
regex = "1"
actix = "0.13"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
once_cell = "1.19"
# moka = { version = "0.12", features = ["future"]}
toml = "0.8"

[features]
use_fern = ["dep:fern"]
