[package]
name = "mangadex-desktop-api2"
version = "0.5.7"
authors = ["tonymushah <tonymushahdev06@yahoo.com>"]
license = "MIT OR Apache-2.0"
description = "A Actix server for downloading manga, chapters, covers from Mangadex"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.20", features = [
    "cookies",
    "json",
    "multipart",
    "rustls-tls"
] }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.48"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
url = { version = "2.4.1", features = ["serde"] }
mangadex-api = { version = "2.3.1", default-features = false, features = ["multi-thread", "utils", "deserializable-endpoint"] }
anyhow = "1.0.75"
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["sync", "rt", "macros", "rt-multi-thread"] }
actix-web = { version = "4" }
mangadex-api-schema-rust = { version = "0.4.1", default-features = false, features = ["serialize"] }
mangadex-api-types-rust = { version = "0.4", default-features = false }
log = "^0.4.20"
fern = {version = "0.6.2", optional = true}
futures = { version = "0.3.28" }
tokio-stream = { version = "0.1"}
async-stream = { version = "0.3"}
bytes = { version = "1.5"}
itertools = "0.11.0"
serde_qs = { version = "0", features = ["actix4"]}
async-trait = "0.1"
actix-cors = "0.6.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"]}

[features]
default = []
use_fern = ["dep:fern"]

[[bin]]
name = "special-eureka-downloader"
required-features = ["use_fern"]

[[bench]]
name = "aggregate"
harness = false