[package]
name = "mangadex-desktop-api2"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.11.2"
futures = { version = "0.3.21", optional = true }
reqwest = { version = "0.11.14", features = [
    "cookies",
    "json",
    "multipart",
    "rustls-tls",
    "blocking"
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_qs = "0.9.2"
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-human-readable"] }
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] }
mangadex-api = { version = "2.0.0-rc.1", features = ["multi-thread"] }
anyhow = "1.0.55"
serde_json = "1.0.79"
tokio = { version = "1.24.2", features = ["full"] }
json = "0.12.4"
actix-web = "4"
actix-files = "0.6.2"
mangadex-api-schema = "0.1.0"
mangadex-api-types = "0.1.0"
derive_more = "0.99.17"
log = "^0.4"
once_cell = "1.17.0"
fern = "0.6.1"

[dev-dependencies]
clap = { version = "3.1.2", features = ["derive"] }
fake = { version = "2.4.3" }
wiremock = "0.5.11"
futures = "0.3.25"