[package]
name = "mangadex-desktop-api2"
version = "1.0.0-alpha.1"
authors = ["tonymushah <tonymushahdev06@yahoo.com>"]
license = "MIT OR Apache-2.0"
description = "A Actix server for downloading manga, chapters, covers from Mangadex"
repository = "https://github.com/tonymushah/eureka-mmanager"
edition = "2021"
resolver = "2"
rust-version = "1.76"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12", features = [
    "cookies",
    "json",
    "multipart",
    "rustls-tls",
], optional = false }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.8", features = ["serde", "v4"] }
url = { version = "2.5", features = ["serde"], optional = false }
mangadex-api = { version = "3.3", default-features = false, features = [
    "rw-multi-thread",
    "utils",
    "serialize",
], optional = false }
serde_json = { version = "1.0", optional = false }
mangadex-api-schema-rust = { version = "0.9", default-features = false, features = [
    "serialize",
], optional = false }
mangadex-api-types-rust = { version = "0.9", default-features = false, optional = false }
tokio = { version = "1.37", features = [
    "sync",
    "rt"
], optional = false }
log = "^0.4.21"
tokio-stream = { version = "0.1", optional = false }
bytes = { version = "1.6", optional = false }
itertools = "0"
mangadex-api-input-types = { version = "0.5", optional = false }
regex = "1"
actix = "0.13"
rand = { version = "0" }
ciborium = { version = "0" }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
once_cell = "1.19"
# moka = { version = "0.12", features = ["future"]}
toml = "0.8"
anyhow = "1.0"

[workspace]
members = ["eureka-manager-cli", "id_list_txt_reader"]
