[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit-files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.publish-core]
workspace = false
command = "cargo"
args = ["publish", "-p", "eureka-mmanager-core"]

[tasks.publish-manager]
workspace = false
command = "cargo"
args = ["publish", "-p", "eureka-mmanager"]

[tasks.publish-emdx]
workspace = false
command = "cargo"
args = ["publish", "-p", "emdx"]

[tasks.publish-ids]
workspace = false
command = "cargo"
args = ["publish", "-p", "id_list_txt_reader"]

[tasks.publish-cli]
workspace = false
command = "cargo"
args = ["publish", "-p", "eureka-mmanager-cli"]

[tasks.download-chapter]
workspace = false
command = "cargo"
args = [
    "run",
    "-p",
    "eureka-manager-cli",
    "--",
    "-v",
    "download",
    "chapter",
    "--id-text-file",
    "./chapters.txt",
]

[tasks.publish-all]
workspace = false
dependencies = [
    "publish-core",
    "publish-manager",
    "publish-emdx",
    "publish-ids",
    "publish-cli",
]
