[config]
default_to_workspace = false

[tasks.format]
workspace = true
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit-files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
workspace = true
command = "cargo"
args = ["clippy"]

[tasks.clippy-fix]
workspace = true
command = "cargo"
args = ["clippy", "--fix"]

[tasks.publish-core]
command = "cargo"
args = ["publish", "-p", "eureka-mmanager-core"]

[tasks.publish-manager]
command = "cargo"
args = ["publish", "-p", "eureka-mmanager"]

[tasks.publish-emdx]
command = "cargo"
args = ["publish", "-p", "emdx"]

[tasks.publish-ids]
command = "cargo"
args = ["publish", "-p", "id_list_txt_reader"]

[tasks.publish-cli]
command = "cargo"
args = ["publish", "-p", "eureka-manager-cli"]

[tasks.download-chapter]
command = "cargo"
args = [
    "run",
    "-p",
    "eureka-manager-cli",
    "--",
    "-v",
    "download",
    "chapter",
    "--id-text-file",
    "./chapters.txt",
]

[tasks.publish-all]
workspace = false
dependencies = [
    "publish-core",
    "publish-manager",
    "publish-emdx",
    "publish-ids",
    "publish-cli",
]
