[package]
name = "edmx"
version = "0.1.0"
edition = "2021"

[dependencies]
api-core = { workspace = true }
tar.workspace = true
zstd.workspace = true
serde.workspace = true
ciborium.workspace = true
thiserror.workspace = true
