name: Rust

on:
  push:
    branches: ["v0.x", "main"]
  pull_request:
    branches: ["v0.x", "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose
      - name: Run checks
        run: cargo clippy --verbose

  test:
    needs: build
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: precompile tests
        run: cargo build --tests --workspace
      - name: run tests
        run: cargo test --workspace --tests --no-fail-fast
  testing_download:
    needs: test
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: prebuild download_test
        run: cargo build --example download_test
      - name: install cargo make
        run: cargo install --force cargo-make
      - name: downloading things...
        run: RUST_LOG=trace cargo make download_test
        timeout-minutes: 5
